### PR TITLE
[ansible/*] added compatibility with Amazon Linux 2

### LINKED ISSUE #206: [Ansible] Make usable for Amazonlinux2 Distribution
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which installer**: Ansible Collection

**Which product and version** (eg: ansible & collection version - 7.24.2): 10.3.2

**Which operating system and version**(eg: ubuntu & version - 20.4): Amazonlinux2

**What happened**: I could not install on an Amazonlinux 2 System

**What you expected to happen**: I would like to use the collection on an Amazonlinux2 System

**How to reproduce it** (as minimally and precisely as possible): Set up an Amazonlinux2 Server and try to install the collection with ansible

### PR DESCRIPTION
**Pull request by MatrixCrawler**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [x] CHANGELOG.md updated

**What this PR does / why we need it**: It adds compatibility with Amazonlinux2

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #206 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by MatrixCrawler** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MatrixCrawler** [comment]
recheck

**Comment by chukka** [comment]
@MatrixCrawler  did you try to test all roles on amazon linux ? can you share logs or final output ? we would like to review this internally in mean time

**Comment by chukka** [comment]
@MatrixCrawler reminder

**Comment by rahulsadanandan** [comment]
@MatrixCrawler did you get a chance to check above comments.

**Pull request closed without merging**
