### PR TITLE
Add imdopotence for artifactory

### PR DESCRIPTION
**Pull request by Serienmorder**
The previous role, due to making certain changes(download and extraction) every run was very inefficient and broke existing installations, this should prevent that.

### CODE REVIEW

**Comment by Serienmorder** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Serienmorder** [comment]
I want to tweak the migration piece. I found that it causes some problems.

**Comment by jefferyfry** [comment]
There are some openshift files included in the PR. Did you mean to include those?

**Comment by Serienmorder** [comment]
> There are some openshift files included in the PR. Did you mean to include those?

I see it's listed as changes, but it says there are 0 changes to those files? That's bizarre

**Comment by Serienmorder** [comment]
Realistically, there is no way to mitigate my changes. No matter what there is a corner case where things won't be covered. Ultimately, if they actually provide their username and password for artifactory, there is no issue. Issue only occurs if they don't set those, and run an upgrade. So I've added a note in the readme and people just need to read it.

**Comment by Serienmorder** [comment]
I'm willing to hear ideas from others if anyone has one.

**Comment by jefferyfry** [comment]
Can you update the CHANGELOG and the version matrix in the README?

**Comment by Serienmorder** [comment]
@jefferyfry Done, and came up with a slightly better way to test if it's installed.

**Review by jefferyfry — APPROVED** [review]
LGTM

**Comment by chukka** [comment]
@Serienmorder I would like to try these changes once  and approve this

**Review by chukka — APPROVED** [review]

**Pull request merged**
