### PR TITLE
ARM template bug fixes and improvements

### PR DESCRIPTION
**Pull request by danielmkn**
- Fixed bug in the Nginx config (not escaped $ characters)
- Postgresql storage increased for Xray and Artifactory, as well as in standalone Postgresql template. Default 5 Gb is not enough for both.  
- Different callhome data is used by the plain VM image and if this image is used in the ARM template (PTRENG-1226)

### CODE REVIEW

**Comment by danielmkn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by danielmkn** [comment]
recheckcla

**Review by peters95 — APPROVED** [review]
LGTM

**Review by vinayagg — APPROVED** [review]

**Comment by danielmkn** [comment]
recheckcla

**Pull request merged**
