### PR TITLE
[ansible/missioncontrol] Fixes #120

### LINKED ISSUE #120: [ansible/missioncontrol] Ansible missioncontrol_version variable typo
**Is this a request for help?**: no
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report
**Which installer**: mission control
**Which product and version** (eg: ansible & collection version - 1.1.2): ansible - latest
**Which operating system and version**(eg: ubuntu & version - 20.4): all
**What happened**: missioncontrol_version is set, but role also expects missionControl_version to be set
**What you expected to happen**: to just set missioncontrol_version
**How to reproduce it** (as minimally and precisely as possible): set just mission_control version and run mission control role

**Anything else we need to know**: the following files and lines have the typos:
Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/defaults/main.yml  | 15
Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/defaults/main.yml | 19
Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/templates/installer-info.json.j2 | 3

### PR DESCRIPTION
**Pull request by clarionhoover**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [x] CHANGELOG.md updated

**What this PR does / why we need it**: Fixes #120 where there are two variables for missioncontrol_version

**Which issue this PR fixes** : fixes #120 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by clarionhoover** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by clarionhoover** [comment]
recheckcla

**Comment by rhooverea** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rhooverea** [comment]
recheckcla

**Comment by chukka** [comment]
Thanks for the PR - we identified this in our internal testing, and  already fixed internally  , It will be released along with next release

**Comment by chukka** [comment]
Closing this , Fix is available in #124 124

**Pull request closed without merging**
