### PR TITLE
[ansible/artifactory] Configures SELinux context for RHEL systems (fixes: #157)

### LINKED ISSUE #157: SELinux preventing artifactory.service from starting (running artifactoryManage.sh manually works fine)
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**: Ansible

**Which product and version** (eg: ansible & collection version - 1.1.2): Ansible 2.9, Collection Version 7.24.3

**Which operating system and version**(eg: ubuntu & version - 20.4): RHEL 8.3 (SELinux running in Enforced mode)

**What happened**:  artifactory.service will fail to start during install

**What you expected to happen**:  artifactory.service to start successfully during deployment

**How to reproduce it** (as minimally and precisely as possible): Set SELinux to enforcement

**Anything else we need to know**:

After checking various logs, I found denies in the selinux logs.  When SELinux is being run in enforcement mode, systemd cannot run artifactoryManage.sh as it doesn't trust the undefined type.

I am able to resolve this by setting the SELinux type for {{jfrog_home}}/artifactory/app/bin/artifactoryManage.sh to bin_t

This issue can be validated by temporarily setting SELinux to permissive and checking that the service will start or by setting the type of the file directly.

Please consider the following change:

From:

=========
- name: Ensure permissions are correct
  become: yes
  file:
    path: "{{ jfrog_home_directory }}"
    group: "{{ artifactory_group }}"
    owner: "{{ artifactory_user }}"
    recurse: yes
=========

To:

=========
- name: Ensure permissions are correct
  become: yes
  file:
    path: "{{ jfrog_home_directory }}"
    group: "{{ artifactory_group }}"
    owner: "{{ artifactory_user }}"
    recurse: yes

- name: Assign bin_t type to artifactoryManage.sh
  sefcontext:
    target: '/opt/jfrog/artifactory/app/bin/artifactoryManage.sh'
    setype: bin_t
    state: present
=========

I am a Linux novice, to be sure, so if there is a better way to handle this for those of us running with SELinux in enforcement, I am open to that.

### PR DESCRIPTION
**Pull request by matthargrave**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Configures the Artifactory bin directory with 'bin_t' SELinux context on RHEL.  This prevents issues from running executables with SELinux set to enforcing

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #157  

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by matthargrave** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
@matthargrave Thanks for the contribution, we will review this internally and would like this fix to be part of next release in coming weeks

**Comment by matthargrave** [comment]
recheck

**Comment by alexeyd-itsoft** [comment]
@matthargrave 

Do we really need explicitly restore context ? As far as I can see from the [doc](https://docs.ansible.com/ansible/latest/collections/community/general/sefcontext_module.html#notes)

**Not applying SELinux fcontexts to existing files is a deliberate decision** as it would be unclear what reported changes would entail to, and there’s no guarantee that applying SELinux fcontext does not pick up other unrelated prior changes.

**Comment by matthargrave** [comment]
@alexeyd-itsoft 
Any new files will have the correct SELinux context, so as long as the configuration is completed prior to the creation of the directory it wouldn't be needed.  My desire to put it in there, was due to unknowns about situations where that directory would already exist.  For example if someone had already ran a previous version that didn't set the correct context and the filesystem wasn't clean up.   

While I am not a fan of using raw commands in Ansible (for obvious reasons), Any issues caused by restoring context would be due to bad configuration, and should not be the reason to avoid this.

**Comment by alexeyd-itsoft** [comment]
@matthargrave 

Thanks for such detailed answer. I will check

**Pull request closed without merging**
