### PR TITLE
Add Apache 2.0 license

### PR DESCRIPTION
**Pull request by lafrenierejm**
The text of the license was retrieved from https://www.apache.org/licenses/LICENSE-2.0.txt.

Addresses part of #142.

### CODE REVIEW

**Comment by lafrenierejm** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
@lafrenierejm  can you please remove .txt extension from LICENSE file .

**Comment by lafrenierejm** [comment]
> can you please remove .txt extension from LICENSE file .

@chukka Done!

**Comment by chukka** [comment]
@lafrenierejm  can you use this license - https://raw.githubusercontent.com/jfrog/charts/master/LICENSE and update PR ?

**Comment by lafrenierejm** [comment]
> can you use this license - https://raw.githubusercontent.com/jfrog/charts/master/LICENSE and update PR ?

Done. I ensured the exact contents of that file were used by `curl`ing it directly into the file:
```
curl https://raw.githubusercontent.com/jfrog/charts/master/LICENSE > LICENSE
```

**Pull request merged**
