### PR TITLE
[ansible/artifactory] Fix for #223 Changing PGDATA

### LINKED ISSUE #223: Changing postgres_data_dir caused postgres service startup to fail
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**:

Postgres

**Which product and version** (eg: ansible & collection version - 7.24.2):

ansible 2.12.6
jfrog.platform 10.6.2

**Which operating system and version**(eg: ubuntu & version - 20.4):

RHEL 8.6

**What happened**:

I changed _postgres_data_dir_ to _/data/postgres/data_.
The platform created the database in the new location and set **PGDATA** to the correct location in _/etc/profile.d/postgres.sh_.
However, the postgresql-13 service failed to start because the following line in _/usr/lib/systemd/system/postgresql-13.service_ was left unchanged.
```
Environment=PGDATA=/var/lib/pgsql/13/data/
```
Error:
```
ExecStartPre=/usr/pgsql-13/bin/postgresql-13-check-db-dir ${PGDATA} (code=exited, status=1/FAILURE)
```
```
/usr/pgsql-13/bin/postgresql-13-check-db-dir /var/lib/pgsql/13/data
"/var/lib/pgsql/13/data" is missing or empty.
Use "/usr/pgsql-13/bin/postgresql-13-setup initdb" to initialize the database cluster.
```

**What you expected to happen**:

The database should come up pointing at the correct location for **PGDATA**.

**How to reproduce it** (as minimally and precisely as possible):

Change the value of _postgres_data_dir_ to anything other than default.

**Anything else we need to know**:

Removing the _Environment=_ line from _/usr/lib/systemd/system/postgresql-13.service_ does not fix it.  Apparently, is must be changed.

### PR DESCRIPTION
**Pull request by bbaassssiiee**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [X] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:

Bugfix. Setting a custom PGDATA directory crashed postgres.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #223

**Special notes for your reviewer**:

More info in the issue #223

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
How to test:

```yaml
- name: Deploy postgres
  hosts: db
  become: true
  gather_facts: true
  vars:
    postgres_enabled: true
  roles:
    - role: postgres
      postgresql_data_dir: /data/postgres/data
```

**Comment by shahiinn** [comment]
Thank you for raising the PR.
We will review it internally and get back to you if any changes are required.

**Comment by chukka** [comment]
@bbaassssiiee can you pls rebase to `jp-10.12.3` branch to fix conflicts   so that I can plan to merge to master

**Comment by chukka** [comment]
@bbaassssiiee Pls squash all your commits to single one

**Pull request merged**
