### PR TITLE
AWS MP 7.27.10

### PR DESCRIPTION
**Pull request by giri-vsr**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by chukka — CHANGES_REQUESTED** [review]
@giri-vsr please change bintray images to `releases-docker.jfrog.io`

**Comment by giri-vsr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by giri-vsr** [comment]
> 
Update Images to releases-docker.jfrog.io

**Review by alexhung — APPROVED** [review]
LGTM :shipit:

**Review by chukka — APPROVED** [review]

**Pull request merged**
