### PR TITLE
Checking in code for rt 7.17.4 version

### PR DESCRIPTION
**Pull request by vinayagg**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by alexhung — CHANGES_REQUESTED** [review]
Looks like files in the submodules directory is added to the repo. They shouldn't, right?

The rest looks ok.

**Comment by vinayagg** [comment]
> Looks like files in the submodules directory is added to the repo. They shouldn't, right?
> 
> The rest looks ok.

I tested and for self hosted ones, submodules also need to be in the s3 bucket from where we deploy, so I think they should be in repo too.

**Comment by alexhung** [comment]
> > Looks like files in the submodules directory is added to the repo. They shouldn't, right?
> > The rest looks ok.
> 
> I tested and for self hosted ones, submodules also need to be in the s3 bucket from where we deploy, so I think they should be in repo too.

Yes, but don't we normally ask engineer to initialize the submodules directory locally first before deploying? I don't feel including the code from submodules is useful. Definitely duplicate.

**Comment by vinayagg** [comment]
> > > Looks like files in the submodules directory is added to the repo. They shouldn't, right?
> > > The rest looks ok.
> > 
> > 
> > I tested and for self hosted ones, submodules also need to be in the s3 bucket from where we deploy, so I think they should be in repo too.
> 
> Yes, but don't we normally ask engineer to initialize the submodules directory locally first before deploying? I don't feel including the code from submodules is useful. Definitely duplicate.

Let me explain the use case.
1. Go to this link https://www.jfrog.com/confluence/display/JFROG/JFrog+Partner+Integrations#JFrogPartnerIntegrations-awscloudformation
2. Search for "Deploy to new VPC", you will find 4 links. click on any of them and try to deploy. This deployment is for end user who is not required to understand submodules or taskcat etc.

**Comment by alexhung** [comment]
I didn't mean customers using the templates. I mean when we update/deploy to S3. But it's fine for now.

**Review by alexhung — APPROVED** [review]

**Pull request merged**
