### PR TITLE
[ansible/xray] Support of RHEL/Centos

### PR DESCRIPTION
**Pull request by Serienmorder**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ x] CHANGELOG.md updated
- [ x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
The role provided did not work. It was not able to install packages according to the correct redhat operating system, and because of that, required these changes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

I'd recommend dropping the postgressql role. I also attempted to fix it, but it got to the point it was easier to switch to one of the very well written roles already available on galaxy.

### CODE REVIEW

**Comment by Serienmorder** [comment]
I'm not sure how to fix the slack pull request issue?

**Comment by chukka** [comment]
@Serienmorder Thanks for  the contribution , we will test this internally and plan to release this fix along with support of distribution and mission control roles early next month.

**Comment by peters95** [comment]
Looks like the Slack pull request notification failed because it did not find the file in the remote repo. Looking into it.

**Comment by Serienmorder** [comment]
I did a rebase before submitting. So I'm not sure why that file didn't come over?

**Pull request closed without merging**
