### PR TITLE
[ansible/artifactory] Update nginx installation on RHEL8/CentOS8 (#167)

### LINKED ISSUE #167: nginx on RHEL8/CentOS8
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
Latest

**Which operating system and version**(eg: ubuntu & version - 20.4):
RHEL 8.4

**What happened**:
nginx installation is requiring epel8, but nginx is not in epel8 in rhel8/centos8 because it is in appstreams.
Now you need to be careful what you do, I suspect the way you now have this set up it will install from the default nginx appstream which is nginx 1.14 -- but that one is not supported anymore in centos/rhel; you need to select the nginx 1.18 appstream.

https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/RedHat.yml
(will install epel 8)
https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/main.yml#L4-L12
will install nginx 1.14 from default appstream

(same for nginx_ssl)

**What you expected to happen**:
Select appstream that is currently supported -- as of today https://access.redhat.com/support/policy/updates/rhel8-app-streams-life-cycle it is nginx 1.18 -- and install nginx from there, do not use epel if that can be avoided

**Anything else we need to know**:
I think you may also need to contact all customers using this code on rhel/centos8 because they are running an nginx that is not being updated anymore

### PR DESCRIPTION
**Pull request by deild**
#### PR Checklist
- [ x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Resolved select nginx 1.18 appstream

**Which issue this PR fixes** 
 fixes #167

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by chukka** [comment]
@deild  Thanks for contribution ! we would like to review and test this internally . can you please sign the CLA

**Comment by Klaas-** [comment]
if you use 1.18 you need to update it in less than 12 months, if you use 1.20 you're safe till Nov 2023 :)

**Comment by deild** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
Thanks. Changes taken in #185

**Pull request closed without merging**
